name: Update README with latest blog posts

on:
  workflow_dispatch:  # ✅ 수동 실행 가능하도록 설정
  push:
    branches: [ master ]  # ✅ master 브랜치에서 실행

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # ✅ GitHub Actions가 README.md를 수정할 권한 부여

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 현재 코드 가져오기

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install  # ✅ `npm ci` 대신 `npm install` 사용
          npm install rss-parser

      - name: Update README with latest blog posts
        run: node index.js  # ✅ 우리가 만든 index.js 실행

      - name: Check for changes
        id: verify_diff
        run: |
          git diff --quiet || echo "changed=true" >> $GITHUB_ENV

      - name: Commit changes
        if: env.changed == 'true'
        run: |
          git config --global user.name "kimyurie"  # ✅ 내 깃허브 계정 사용
          git config --global user.email "9911dbfl@naver.com"  # ✅ 내 깃허브 이메일 사용
          git add README.md
          git commit -m "Update README with latest blog posts"
          git push origin master  # ✅ master 브랜치로 푸시
